[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[build.environment]
  NPM_VERSION = "6.12.0"

[[headers]]
  for = "/static/*"
    [headers.values]
    cache-control = 'public, max-age=360000'
  for= "/static/fonts/*"
    [headers.values]
    access-control-allow-origin = '*'

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
