[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[build.environment]
  NPM_VERSION = "6.4.1"

[[headers]]
  for = "/static/*"
    [headers.values]
    cache-control = 'public, max-age=360000'

# [[headers]]
#   for = "/*"
#     [headers.values]
#     Basic-Auth = "teamflow:letsgo florin:letsgo"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
