backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  - name: blog-post
    label: Blog
    folder: src/content/blog
    extension: mdx
    format: frontmatter
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Template Key'
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: 'Publish Date'
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Color
        name: color
        widget: select
        options: ['pink', 'indigo', 'yellow', 'green', 'blue', 'purple']
        default: 'blue'
      - label: 'Featured Image'
        name: featuredimage
        widget: image
      - label: 'Social Image'
        name: socialimage
        widget: image
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
  - name: pages
    label: Pages
    extension: mdx
    format: frontmatter
    files:
      - file: src/content/index.mdx
        label: 'Home Page'
        name: index
        fields:
          - label: 'Template Key'
            name: templateKey
            widget: hidden
            default: index-page
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
          - label: Experiments
            name: experiments
            widget: list
            fields:
              - label: ID
                name: id
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Date
                name: date
                widget: date
      - file: src/content/blog/index.mdx
        label: Articles
        name: blog
        fields:
          - label: 'Template Key'
            name: templateKey
            widget: hidden
            default: blog-page
          - label: Title
            name: title
            widget: string
      - file: src/content/about/index.mdx
        label: About
        name: about
        fields:
          - label: 'Template Key'
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Bio Image
            name: bioimage
            widget: image
          - label: Bio
            name: bio
            widget: text
          - label: Involvement
            name: involvement
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Project
                name: project
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Description
                    name: description
                    widget: text
                  - label: Link
                    name: link
                    widget: string
          - label: What I Use
            name: what-i-use
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Usage
                name: usage
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Description
                    name: description
                    widget: string
                  - label: Link
                    name: link
                    widget: string
                  - label: Icon
                    name: icon
                    widget: string
          - label: Skillset
            name: skillset
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Skill
                name: skill
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
      - file: src/content/resume/index.mdx
        label: Resume
        name: resume
        fields:
          - label: 'Template Key'
            name: templateKey
            widget: hidden
            default: resume-page
          - label: Title
            name: title
            widget: string
          - label: Employment History
            name: history
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Job
                name: job
                widget: list
                fields:
                  - label: Company
                    name: company
                    widget: string
                  - label: Position
                    name: position
                    widget: string
                  - label: Start Date
                    name: startdate
                    widget: string
                  - label: End Date
                    name: enddate
                    widget: string
                  - label: Description
                    name: description
                    widget: markdown
                    minimal: true
                    buttons: ["bulleted-list"]
                    editorComponents: []
          - label: Education
            name: education
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: markdown
                minimal: true
                buttons: ["italic"]
                editorComponents: []
          - label: Tools
            name: tools
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Tool
                name: tool
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
          - label: Open-Source Projects
            name: opensource
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Project
                name: project
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Link
                    name: link
                    widget: string
  - name: project
    label: Project
    folder: src/content/work
    extension: mdx
    format: frontmatter
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Template Key'
        name: templateKey
        widget: hidden
        default: project
      - label: Title
        name: title
        widget: string
      - label: 'Publish Date'
        name: date
        widget: datetime
      - label: Role
        name: role
        widget: string
      - label: Description
        name: description
        widget: text
      - label: 'Cover Image'
        name: coverimage
        widget: object
        fields:
          - label: Light
            name: light
            widget: image
          - label: Dark
            name: dark
            widget: image
          - label: Shadow
            name: shadow
            widget: boolean
            default: true
      - label: Section
        name: section
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: text
          - label: 'Section Image'
            name: sectionimage
            widget: object
            fields:
              - label: Light
                name: light
                widget: image
              - label: Dark
                name: dark
                widget: image
              - label: Shadow
                name: shadow
                widget: boolean
                default: true
              - label: Alt
                name: alt
                widget: string
